### ISSUE TITLE
Fix Font

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#23]
When you have maximized screen or fullscreen then the font on tabgui is fucked and not clear but in small window mode it is

**Comment by OxideWaveLength** [comment]
I am aware of this issue, but unfortunately the problem is with the FontManager, which I did not make.
You can temporarily fix the issue by setting the Gui Scale in the Video Settings to "normal" (or "auto" if your screen is 1920x1080p)

![GuiScale](https://user-images.githubusercontent.com/60556091/74061576-9b9ba600-49ec-11ea-954f-83f2f310dba9.png)

**Comment by OxideWaveLength** [comment]
Fixed in the commit ce7f451
