### ISSUE TITLE
TabGUI cycle crash

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#25]
I was trying to make a `moduleSettings.set("speed", 10F);`
But when i went into the game 99% it crashed
else it just did nothing

Am i using it wrong? because i wanna change my speed thats in a `public float speed = 10;`

**Comment by mymonsterdk** [comment]
ok i figured it out. But still look at the crashing because it crashes if their is no changeable value

**Comment by OxideWaveLength** [comment]
I will look into it right now, will let you know if I can replicate the issue

**Comment by OxideWaveLength** [comment]
Can you tell me where you put the `moduleSetting.set("speed", 10F)`?
There is the `moduleSettings.addDefault(String key, Object value)` that will set, in this case, "speed" to 10F only if the value does not exist. And there is also a `#setup()` method you can override in the Module class (see the Fly or TestModule) to set these default values.

If the code that made your client crash was in the `onUpdate()` it probably happened because every time the `moduleSettings#set()` method is called it will save the file, which will be not be accessible for a few seconds after since it is locked by the system to be saved

**Comment by mymonsterdk** [comment]
ah ok. That was the issue then. BTW can you do so you can disable the extra extension so like if a module dont have any settings then it cant go further than to the big list of all modules

**Comment by OxideWaveLength** [comment]
![image](https://user-images.githubusercontent.com/60556091/74090266-93557080-4aa9-11ea-9e9a-a8a537459fd2.png)
You mean this? Could you open a new issue for that?

**Comment by mymonsterdk** [comment]
yes
